/**
 * Grant 'access toolbar', 'use text format full_html',
 * 'use text format filtered_html'permissions for sharing3fvg role.
 */
function grant_permissions_update_7001() {
  $permissions = array(
    'access toolbar',
    'use text format full_html',
    'use text format filtered_html',
    );
  $role = user_role_load_by_name('sharing3fvg');
  user_role_grant_permissions($role->rid, $permissions);
}
